<?php

namespace TomatoPHP\FilamentTypes\Tests\Pages;

use Filament\Pages\Dashboard;
use TomatoPHP\FilamentTypes\Pages\BaseTypePage;
use TomatoPHP\FilamentTypes\Services\Contracts\Type;

class TypePage extends BaseTypePage
{
    public function getTitle(): string
    {
        return 'Notes Groups';
    }

    public function getType(): string
    {
        return 'groups';
    }

    public function getFor(): string
    {
        return 'notes';
    }

    public function getBackUrl()
    {
        return Dashboard::getUrl(); // TODO: Change the autogenerated stub
    }

    public function getTypes(): array
    {
        return [
            Type::make('todo')
                ->name('TODO')
                ->color('#1461e3')
                ->icon('heroicon-o-list-bullet'),
            Type::make('ideas')
                ->name('Ideas')
                ->color('#13e0da')
                ->icon('heroicon-o-sparkles'),
            Type::make('saved')
                ->name('Saved')
                ->color('#29a82e')
                ->icon('heroicon-o-arrow-down-on-square'),
        ];
    }
}
